### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by greenduck** [maoschanz/gedit-plugin-markdown_preview#10]
Ubuntu 16.04, gedit 3.18.3.
Upon selecting the plugin, and upon any consecutive gedit start - segmentation fault immediately.

**Comment by maoschanz** [comment]
I don't know what version of the plugin you're using, but it's not very ready to use anyway, i keep changing how it works so half of the features are broken

However, a segfault with a **python** plugin is very unusual: does the terminal really say "segmentation fault" or does it say something about a Gio error and a schema not installed?

**Comment by greenduck** [comment]
My terminal output:
> ~/Work$ gedit 
> Segmentation fault

I've just cloned your repository, so it's your commit 43639d66.

**Comment by maoschanz** [comment]
>(WIP)

Cloning this was not a very wise move 😔 (anyway it really shouldn't segfault, the WIP features are the export dialog and the plugin's preferences dialog)

What you can try:

- run uninstall as a normal user
- then try to install it as root
- if it still don't work, run the uninstall script as root and tell me, maybe gedit just has a bug in their older API

**Comment by maoschanz** [comment]
ok i tested, and even when i disable a bunch of things it still doesn't work, so this plugin is just not compatible with 16.04
