### ISSUE TITLE
no preview on Fedora 30

### ISSUE THREAD

**Issue by tackephap** [maoschanz/gedit-plugin-markdown_preview#11]
I made a change on the install.sh script since on Fedora 30 all plugins are stored on /usr/lib64/gedit/plugins.

beside the command glib-compile-schemas /usr/share/glib-2.0/schemas return several warning:
```
Warning: Schema “org.freedesktop.ibus” has path “/desktop/ibus/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.freedesktop.ibus.general” has path “/desktop/ibus/general/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.freedesktop.ibus.general.hotkey” has path “/desktop/ibus/general/hotkey/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.freedesktop.ibus.panel” has path “/desktop/ibus/panel/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.freedesktop.ibus.panel.emoji” has path “/desktop/ibus/panel/emoji/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.crypto.cache” has path “/desktop/gnome/crypto/cache/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.crypto.pgp” has path “/desktop/gnome/crypto/pgp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
```

Even i can see the plugin options and the "Markdown Preview" windows on the side panel on Gedit, i still have no preview(blank "Markdown Preview" windows) of any .MD files.

**Comment by maoschanz** [comment]
>I made a change on the install.sh script since on Fedora 30 all plugins are stored on /usr/lib64/gedit/plugins.

You could have executed it without sudo

>beside the command glib-compile-schemas /usr/share/glib-2.0/schemas return several warning:

None of them concern my plugin, if GNOME has deprecated schemas you should report it to them

>Even i can see the plugin options and the "Markdown Preview" windows on the side panel on Gedit, i still have no preview(blank "Markdown Preview" windows) of any .MD files.

What is printed by gedit if it's launched from a terminal?

**Comment by eexpress** [comment]
```
** (org.gnome.gedit:6245): WARNING **: 15:11:25.086: Error importing plugin 'markdown-preview':
Traceback (most recent call last):
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/eexpss/.local/share/gedit/plugins/markdown-preview/__init__.py", line 21, in <module>
    from gi.repository import Gdk, Gtk, Gedit, GObject, WebKit
  File "/usr/lib64/python3.7/site-packages/gi/importer.py", line 133, in load_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name WebKit, introspection typelib not found

(org.gnome.gedit:6245): libpeas-WARNING **: 15:11:25.086: Error loading plugin 'markdown-preview'
```

**Comment by maoschanz** [comment]
```
File "/home/eexpss/.local/share/gedit/plugins/markdown-preview/__init__.py", line 21, in <module>
    from gi.repository import Gdk, Gtk, Gedit, GObject, WebKit
```

For several reasons, i think you're reporting a bug to the wrong "markdown preview" plugin (i know there were other before mine, i've never tested them so i don't know how up-to-date they are):
- The line 21 of your `__init__.py` is `from gi.repository import Gdk, Gtk, Gedit, GObject, WebKit`, which is not the case here https://github.com/maoschanz/gedit-plugin-markdown_preview/blob/master/markdown_preview/__init__.py and i don't find what point in my commit history matches your error.
- Aside the line number, the fact that **WebKit** is being imported instead of **WebKit2** (which i've always used, and which i import in preview.py but not in `__init__.py` since last month) let me think you enabled a plugin which is not mine
- the plugin is identified as `markdown-preview` while mine is `markdown_preview`

The error also implies that:
- It has been installed as a normal user. If you have also installed it with `sudo`, the user-wide version is the code that will be executed. You can either delete the user-wide version so the system-wide version will be used, or re-install the plugin as a normal user to replace the former files
- I'm not familiar with Fedora packages but if i believe the descriptions from [this website](https://apps.fedoraproject.org/packages/s/webkit%2520gtk) i think the error is that you don't have the package pywebkitgtk (if you want to try *my* plugin instead of yours, the dependency will be webkit2gtk3)

**Comment by eexpress** [comment]
sorry. my fault. Maybe I used an fork version. After I reinstall your version, works well. thanks. :D

**Comment by tackephap** [comment]
Sorry for the late answer:

_"You could have executed it without sudo"_
> I did, even i don't have any error or warning in the output, i didn't had any preview, that's the reason i tried with SUDO.
However, i did unsinstall , remove any trace of it, then reinstall from https://github.com/maoschanz/gedit-plugin-markdown_preview.git
Here the output:
$ ./install.sh
Checking if adequate folders exist…
Installing setting schemas in /home/lolo/.local/share/glib-2.0/schemas
Installing plugin files in /home/lolo/.local/share/gedit/plugins
Done.

_None of them concern my plugin, if GNOME has deprecated schemas you should report it to them_
> I can't tell, i just wanted to show you all output i had to help you to troubleshot the issue.

_What is printed by gedit if it's launched from a terminal?_
>nothing, check the screenshot here
https://photos.app.goo.gl/4ymjYnHfnQHVU4368

**Comment by tackephap** [comment]
**_You could have executed it without sudo_**
> I did, even i don't have any error or warning in the output, i didn't had any preview, that's the reason i tried with SUDO.
However, i did unsinstall , remove any trace of it, then reinstall from your [repo](https://github.com/maoschanz/gedit-plugin-markdown_preview.git)
Here the output:
$ ./install.sh
Checking if adequate folders exist…
Installing setting schemas in /home/lolo/.local/share/glib-2.0/schemas
Installing plugin files in /home/lolo/.local/share/gedit/plugins
Done.

_**None of them concern my plugin, if GNOME has deprecated schemas you should report it to them**_
> I can't tell, i just wanted to show you all output i had to help you to troubleshot the issue.

**_What is printed by gedit if it's launched from a terminal?_**
>nothing, check the screenshot [here](https://photos.app.goo.gl/4ymjYnHfnQHVU4368)

**Comment by maoschanz** [comment]
oops i didn't notice it was someone else who answered (so much activity on this repo!)

**Comment by maoschanz** [comment]
If pandoc was installed it would be printed in the terminal, so i guess you're trying to use `python3-markdown`. It looks like Fedora has dozens of python packages providing markdown to html converters, which one did you install?

**Comment by tackephap** [comment]
I didn't install any, i found the 2 following when i installed your plug-in, so didn't try any other:
webkit2gtk3.x86_64                                2.26.1-3.fc30                         @updates                  
webkit2gtk3-jsc.x86_64                            2.26.1-3.fc30                         @updates

**Comment by tackephap** [comment]
sorry, i misunderstood, here the python package i did installed before install your plugin
python3-markdown.noarch                           2.6.11-5.fc30                         @fedora

**Comment by tackephap** [comment]
Here the list of python mrkdown package avalaible:
$ sudo dnf search markdown | grep -i python
Last metadata expiration check: 2:09:44 ago on jeu. 07 nov. 2019 14:17:44 +07.
python3-markdown.noarch : Markdown implementation in Python
python2-markdown.noarch : Markdown implementation in Python
python3-markdown.noarch : Markdown implementation in Python
python2-markdown2.noarch : A fast and complete Python implementation of Markdown
python3-markdown2.noarch : A fast and complete Python implementation of Markdown
python3-django-markdownx.noarch : A comprehensive Markdown editor built for
python3-pygments-markdown-lexer.noarch : A Markdown lexer for Pygments to
python2-mistune.x86_64 : Markdown parser for Python
python3-mistune.x86_64 : Markdown parser for Python
python2-m2r.noarch : Markdown to reStructuredText converter
python3-m2r.noarch : Markdown to reStructuredText converter
python2-html2text.noarch : Convert HTML to Markdown-formatted text
python3-html2text.noarch : Convert HTML to Markdown-formatted text
python3-gfm.noarch : Github-Flavored Markdown for Python-Markdown
mkdocs.noarch : Python tool to create HTML documentation from markdown sources
python3-pelican.noarch : A tool to generate a static blog from reStructuredText

**Comment by maoschanz** [comment]
i'll try this evening if it's the package expected by the plugin, meanwhile you can try:

- to refresh the preview, because the automatic reloading is likely disabled by default and depending on how gedit starts it may load the preview before the file
- or to install pandoc, and to enable it in the plugin's options (https://user-images.githubusercontent.com/19996113/68207063-6a1ad500-ffce-11e9-9bc9-ef87bd9bfc13.png), so if the problem comes from `python3-markdown` it would be fixed

**Comment by tackephap** [comment]
Ok, it's work now with python3-markdown.
I didn't saw the option Tab "Backend" when i installed it, it was set to "pandoc" by default. I switch to "python3-markdown" and now i can see the preview.
Désolé pour le dérangement.
You can close this issue. Many thanks

**Comment by maoschanz** [comment]
>it was set to "pandoc" by default

Very weird, even if it was convinced pandoc was installed, any attempt to call it should have produced a huge error trace in the terminal 🤔

With the last commit, it now correctly detects if pandoc is installed, and it should force the setting to "python3-markdown" automatically at startup if it's not available
