### ISSUE TITLE
issue with pandoc and python3-markdown

### ISSUE THREAD

**Issue by aysunrhn** [maoschanz/gedit-plugin-markdown_preview#16]
I have just installed the plugin, but I keep getting the "please install pandoc or python3-markdown" warning and I can't generate a preview even though I have both packages installed.

**Comment by maoschanz** [comment]
If you do these commands

```
which pandoc
echo $?
```
does the 2nd one say `0` ?

**Comment by aysunrhn** [comment]
> If you do these commands
> 
> ```
> which pandoc
> echo $?
> ```
> 
> does the 2nd one say `0` ?

Yep. I get 0. I have pandoc installed through conda, so the binary in conda directory is in my path.
 
But I noticed I was actually mixing up the python3-markdown package with the markdown package. I had markdown only, so installing python3-markdown solved the issue. But then again, I should have been able to use it with pandoc only I guess?

**Comment by maoschanz** [comment]
yes you should, the code is pretty straightforward https://github.com/maoschanz/gedit-plugin-markdown_preview/blob/da514d21527cc08e85e9972fe840a6ddf2c0a3a3/markdown_preview/preview.py#L16 i've no idea what didn't work

**Comment by aysunrhn** [comment]
> yes you should have been, the code is pretty straightforward
> 
> https://github.com/maoschanz/gedit-plugin-markdown_preview/blob/da514d21527cc08e85e9972fe840a6ddf2c0a3a3/markdown_preview/preview.py#L16
> 
> i've no idea what didn't work

Yeah, I'll look into the code and try to reproduce the issue when I have time after the holidays. I'll let you know if I find something!

**Comment by maoschanz** [comment]
i close this because i've changed this code entirely
