### ISSUE TITLE
3rd-party extensions support for checkbox

### ISSUE THREAD

**Issue by fla5** [maoschanz/gedit-plugin-markdown_preview#17]
(- [ ] checkbox) doesn't work.

[i edit your comment to have actually useful checkboxes!]

- [x] display non-standard plugins in the UI (if any is set)
- [x] an entry to add such 3rd party plugins
- [x] an help label to explain what it is, with a link to some webpage maybe
- [x] find a plugin to actually display checkboxes and try it

**Comment by maoschanz** [comment]
that's not standard markdown at all. It might work with `python3-markdown` 3rd-party extensions, but i didn't even implement proper support for the default extensions yet

**Comment by maoschanz** [comment]
With the current code, it works like that:

- install pip3 (`sudo apt install python3-pip` if you're using debian)
- install a [third-party extension](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions) such as [this one](https://github.com/FND/markdown-checklist): `pip3 install markdown-ckecklist`
- in my gedit plugin's options:
  - go to the "backend" tab
  - select the "python3-markdown" backend
  - in the entry type `markdown_checklist.extension`
  - and click the "add" button
- close the options and refresh the preview

(**WARNING:** i changed 500 lines but tested almost nothing so there might be even more bugs than before with the current code, i emphasized that this software is still not reliable and not released)

**Comment by maoschanz** [comment]
![Capture d’écran de 2020-01-19 18-58-32](https://user-images.githubusercontent.com/19996113/72685788-c1b8df00-3aed-11ea-90b3-2174d7e88c0e.png)

in my opinion it's kinda fixed
