### ISSUE TITLE
Unable to change preview styles

### ISSUE THREAD

**Issue by ArindamHans** [maoschanz/gedit-plugin-markdown_preview#19]
The current preview style is hard to read. ( Image below) -
![image](https://user-images.githubusercontent.com/39364391/73955781-e99ba580-4929-11ea-8e5f-5825b48fa2b6.png)

I tried changing it by changing the `example.css` and then to make sure then I **uninstalled** and **installed** the plugin via the script. But still no change.

**Comment by maoschanz** [comment]
this file is just an example, it's not used by the plugin by default.

In the plugin's options, you have a button, probably labeled "select a css file": click on it and set the css file you want

**Comment by AGI-chandler** [comment]
> In the plugin's options, you have a button, probably labeled "select a css file": click on it and set the css file you want

I tried that but it doesn't do anything.  Are there certain requirements for the CSS file?  because mine is very simple just to get rid of the bright white background:
```
body{
  background-color: #001B33;
  color: #000000;
}
```
