### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/gedit-plugin-markdown_preview#2]
todo

**Comment by nekohayo** [comment]
I'm going to venture a guess that your code tries to update everything in realtime all the time? If so, consider refreshing the preview using a timeout-based approach, like what was done for GTG: https://fortintam.com/blog/gtg-0-5-released/ (ctrl+F "timeout")

**Comment by maoschanz** [comment]
yes that's the issue

although in 2018 it was worse because it called the pandoc executable at each key release, nowadays at least it relies on an actual python3 module
