### ISSUE TITLE
About packaging

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/gedit-plugin-markdown_preview#22]
Please don't package the master branch, stable versions of this plugin are in the "Releases" tab.

~~(Yes, it's empty for now.)~~ not anymore!

**Comment by maoschanz** [comment]
@yochananmarqos i'm doing this annoucement because i see this https://forum.manjaro.org/t/favorite-lesser-known-apps/57320/417

Currently there are literally "TODO"s written in the UI lol

**Comment by yochananmarqos** [comment]
Too late, I already did. ;P

Would you like me to request the AUR package be deleted for now? I just thought I'd share it since I enjoyed it.

**Comment by maoschanz** [comment]
Well... that's GPL3, so "no guarantee", i guess people know that and i hope they will remember it when they'll see all the bugs.

The package can stay on AUR but don't advertize it too much until i finish the plugin and close this issue

**Comment by yochananmarqos** [comment]
Might be a little too late for that, depending on how many [Linux Uprising](https://www.linuxuprising.com/2020/02/how-to-add-markdown-support-to-gedit.html) readers there are.

**Comment by maoschanz** [comment]
oops 😅 too late indeed

the bugs i know include things like unusable settings dialog for pandoc and revealjs, broken CSS with pandoc, and inconsistent behavior regarding splitters with HTML files. It makes the article kinda lying about these features, but... well the files are still previewed. So nevermind, they'll report the bugs they find if it really bothers them

**Comment by yochananmarqos** [comment]
While we're here, I was going to ask...

> maybe libwebkit2gtk-4.0-37

...does it really need it or not? 🤔️

**Comment by maoschanz** [comment]
i'm 100% sure i need webkit2gtk, and this is the only package i found with that name in the debian repos. But is it the correct one? does it works with some other versions? Do i need something for the GObject Introspection witchcraft? (is `python3-gi` enough? isn't it already a dependency of gedit?)

I didn't really dig into this. On an usual GNOME system, webkit2gtk is already installed anyway

**Comment by yochananmarqos** [comment]
Ah okay, on Arch it's `webkit2gtk`. I'll add it to dependencies. I'm not really sure about Debian.

Yes, `python-gi` (`python-gobject` on Arch) is a dependency of `gedit`. However, `python-gobject` depends on `pygobject-devel` which only depends on `gobject-introspection-runtime`, not `gobject-introspection` itself. `gobject-introspection` depends on `gobject-introspection-runtime`, not the other way around.

**Comment by maoschanz** [comment]
>For python3-markdown there are some extensions available that you can enable from the plugin settings (if you have pymdown-extensions installed)

i missed that part

python3-markdown comes with a default set of extensions, that i listed in the prefs dialog. They work regardless of whether pymdown is installed or not. Pymdown is just an example of good 3rd-party extensions that i suggest, but they will not be listed in the UI until you add their names manually (writing `pymdownx.tasklist` in the text entry for example, and click on "add")

**Comment by logix2** [comment]
Hi. Author of the blog post here :) Adding Markdown tags via right click works for me: https://streamable.com/cjofl But as you can imagine, I didn't try all the features. I'll add a note with what you said it's not currently working in the article.

**Comment by logix2** [comment]
By the way, the package ``libwebkit2gtk-4.0-37`` is the same name from Ubuntu 18.04 to 20.04, so it's the correct package to install:
- [Ubuntu 18.04](https://launchpad.net/ubuntu/+source/webkit2gtk/2.26.4-0ubuntu0.18.04.1)
- [Ubuntu 20.04](https://launchpad.net/ubuntu/+source/webkit2gtk/2.26.4-1ubuntu1)

**Comment by logix2** [comment]
I looked through the source. On Debian/Ubuntu, the only dependency that's not already satisfied via Gedit (not a dependency of Gedit) is ``gir1.2-webkit2-4.0`` (which itself depends on ``libwebkit2gtk-4.0-37`` anyway).

**Comment by maoschanz** [comment]
Ok thanks i'll update the readme

**Comment by yochananmarqos** [comment]
I didn't forget. I'll make a stable version which will be available [here](https://aur.archlinux.org/packages/gedit-plugin-markdown_preview) when I get around to it.

**Comment by maoschanz** [comment]
thank you!

be careful with what the readme pretends though, to export as pdf with pandoc the system needs (on debian sid at least) yet another dependency and i haven't found which one yet

**Comment by yochananmarqos** [comment]
`pdflatex` is part of `texlive-bin` and `lmodern` is part of `texlive-core` if that's what you mean.

**Comment by maoschanz** [comment]
no i mean i have this error https://www.reddit.com/r/pandoc/comments/hanksn/conversion_to_pdf/ but it's probably because of debian

**Comment by yochananmarqos** [comment]
`xcolor.sty` is part of `texlive-core` on Arch. I don't know why Debian has to have so many separate packages. It's annoying when trying to figure out what a project's dependencies are by the control file as they do not list dependencies assumed to be installed.

**Comment by maoschanz** [comment]
You don't need those texlive packages to render the preview itself, but if you want to export the markdown file to a pdf file using pandoc, pandoc will use these texlive packages anyway because i think it uses .tex as an intermediate format during the conversion

However notice that pandoc itself is optional:

- If pandoc is installed but these packages aren't, the preview will work, but exporting to PDF will not. It shouldn't crash though, errors are handled: users will get a dialog window with the error message from pandoc, they might understand what they need to install from this message? If such a concept exists with Arch, i think the texlive packages shouldn't come by default but could be "recommended" instead.
- If pandoc isn't installed at all, the situation is easier: `python3-markdown` will be used instead to render and export, and pandoc-related options will be entirely hidden from the GUI. The negative side is that the file can only be exported as HTML with this...

**Comment by yochananmarqos** [comment]
Ah, okay. This is my current VCS [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gedit-plugin-markdown_preview-git). Pandoc and Tex stuff are optional while `python-markdown` is required.

**Comment by yochananmarqos** [comment]
Stable version is [live](https://aur.archlinux.org/packages/gedit-plugin-markdown_preview).

**Comment by maoschanz** [comment]
Thank you, i'll add it to the readme
