### ISSUE TITLE
Similar plugin

### ISSUE THREAD

**Issue by darkdragon-001** [maoschanz/gedit-plugin-markdown_preview#24]
I just released a fixed version of the `gedit-markdown` plugin: https://github.com/darkdragon-001/gedit-markdown

Would you like to combine our efforts?

**Comment by maoschanz** [comment]
it looks like your readme hasn't changed since you began your fork, could you describe the current state of your plugin and its features?

----

Then concerning "combining our efforts", why not, but it looks like our projects are quite different, mainly because mine can use pandoc to convert from MD to HTML

What needs work in my plugin is:

- keyboard shortcuts for inserting and removing markdown tags (WIP)
- ability to customize the command line used to preview with pandoc
- and, in this regard, provide a user-friendly UI to preview or export as a revealjs slideshow

And what works fine is:

- preview in the panel the user wants
- search in the preview
- zoom in/out
- render the document using python3-markdown with
  - a customizable list of plugins
  - CSS provided by the user
- export the document using python3-markdown

**Comment by darkdragon-001** [comment]
Some other people and myself tried to get the original maintainer to respond to pull requests and issues for several years - without success. I updated the README to the current state (only the pictures are a bit outdated). See [my release announcement](https://github.com/jpfleury/gedit-markdown/issues/16#issuecomment-622458806) on what has changed in the last days.

Features
- Render markdown (`python3-markdown` + plugins)
- Preview (`WebKit2.WebView`)
- Auto-refresh
- Interaction with `GtkSource`'s `LanguageManger` for type detection  
  _→ Just search for "language" in my source code :wink:_
- Convert to PDF via _External Tools_ plugin (using `pandoc`)  
  _This was just a small hack but works_

Missing features
- Plugin preferences GUI _→ your plugin is doing very well here!_
- Keyboard shortcuts for markdown tags (as requested in jpfleury/gedit-markdown#5)  
  _I think not many are needed here: bold, italic, underline, list_
- Preview interaction _→ your plugin is doing very well here!_
  - Search
  - Zoom

I see my plugin as a lightweight preview and therefore would prefer not to have a hard dependency on `pandoc`. As additional converters in form of _External Tools_ is fine for me. For more complex markdown projects, I use Atom with its plugins anyways.

**Comment by maoschanz** [comment]
it's not a hard dependency, most of the useless complexity of my code actually comes from managing cases where there is only python3-markdown but not pandoc, or the opposite

**Comment by darkdragon-001** [comment]
What about wrapping the rendering part behind a common interface? Then you just have to call `renderer.render()`. And on creation you decide if `renderer` is a `RendererPandoc` or `RendererPython` based on availability?

In my code the rendering is a single call to `python3-markdown`. Of course `pandoc` has a lot more options which you want to reveal on the GUI, but something like `renderer.registerYourCallbacks()` and `renderer.showYourOptions()` should still work with the approach depicted above.

**Comment by maoschanz** [comment]
that would be worse imho: the rendering part is simple enough to be a single if, while the several GUIs have nothing in common, so doing a generic interface would be more complicated

anyway my code is uselessly spaghetti but it works quite well (except the 3 things i listed)

i'll probably add support for GtkSource's LanguageManager, i didn't do it at first for some reason i forgot, but i'm sure this reason isn't valid anymore

**Comment by darkdragon-001** [comment]
> i'll probably add support for GtkSource's LanguageManager, i didn't do it at first for some reason i forgot, but i'm sure this reason isn't valid anymore

One downside is the case when the file isn't saved already, one has to select the language manually. But in this case, your detection by file extension fails as well anyways.

---

One thing I didn't get working is having the preview stay at the same position after refresh.
The `ScrolledWindow` as well as the `WebView` both were supporting 0 for all positions / widths... Did you get this working?

**Comment by maoschanz** [comment]
To get it working i had to run some javasript in the webview, search "javascript" in preview.py

However i connected to method to the first random signal that kinda worked, i think there are improvements to do lol

**Comment by darkdragon-001** [comment]
Thanks for this idea! Unfortunately, I couldn't find any better signals as well...
