### ISSUE TITLE
adding markdown_checklist crashed the plugin

### ISSUE THREAD

**Issue by MohitKS5** [maoschanz/gedit-plugin-markdown_preview#27]
I tried adding `markdown-checklist` and `markdown_checklist ` separately, both crashes the preview

**Comment by maoschanz** [comment]
if you start gedit from a terminal, do you have any error message written in this terminal?

**Comment by maoschanz** [comment]
Since you don't answer, i'll consider that you're just trying to load python3-markdown extensions that are incompatible with each other, and that my gedit plugin is not involved at all in the problem

If it's not the case, feel free to provide the requested information and i'll reopen the issue
