### ISSUE TITLE
Nicer formatting of blockquotes and code blocks by default

### ISSUE THREAD

**Issue by nekohayo** [maoschanz/gedit-plugin-markdown_preview#36]
I realize that in theory the plugin supports custom stylesheets, but I really think it should show code and blockquote blocks in a visually distinctive way _by default..._ that's kind of the main reason I'm even using a markdown preview plugin in the first place, because Gedit doesn't show a clear visual distinction for `>` blockquote paragraphs.

Matching the looks of https://www.markdownguide.org/basic-syntax#blockquotes-1 (with a vertical bar; [Marktext](https://marktext.app/) does that too) and https://www.markdownguide.org/basic-syntax#code could do the trick, if you're looking for some inspiration.

**Comment by maoschanz** [comment]
All the HTML tags in your example website are correctly rendered in the preview: then I'm not responsible for the ugly rendering of unstyled blockquotes by webkit2...

for this issue, the answer is in your question: this plugin supports CSS, you can set any CSS file using the options window

if the user says "no css", then it has to be literally no css, and if they say "this css", it has to be this css, there is no case for "css to apply for that specific tag if there is no stylesheet"

-----

If i set the stylesheet i downloaded from your example:

![Capture d’écran de 2021-06-21 21-13-50](https://user-images.githubusercontent.com/19996113/122815547-e2362b80-d2d5-11eb-838e-6b683a1a69e8.png)

well it lacks margins but you get the idea the tag is here. If you don't want to waste your time with this demoniac language, i provide an example CSS file that looks nice in my opinion.
