### ISSUE TITLE
Remember chosen splitter

### ISSUE THREAD

**Issue by ArcWandx86** [maoschanz/gedit-plugin-markdown_preview#38]
I love what you're doing here! This is the only working gedit Markdown plugin that I've seen, and it works fantastic! It's unfortunate that it isn't possible for the preview to autoscroll in sync with the editor; however, I've found that splitting the document at level 2 headers is a great workaround.

However, after closing and reopening gedit, the plugin does not remember which view mode I selected prior, instead always defaulting to showing the whole document. I tried to at least semi fix this using `gsettings` to change `splitter` in `org.gnome.gedit.plugins.markdown_preview` from `whole` to `h2`. However, this seemed to have no effect.

Is it possible to perhaps give an option for the plugin to remember what setting the splitter is set to? Also, would be nice if there were a few more headings we could split by, as even with the small list that I'm working on now, I almost have to scroll on some of the pages.

Obviously not that big of a priority, but just a few things that I noticed + thought I'd give feedback on.

**Comment by ArcWandx86** [comment]
Splitting at page breaks could help a bit for me, actually. Normally I don't use them, but this would be a fairly good use case. However, I would like to note small issue with how you handle that—it appears that the plugin only realizes that a page break exists when there are at least 4 hyphens (`----`) ([line 15](https://github.com/maoschanz/gedit-plugin-markdown_preview/blob/0aee516277f9d1f84adf5ee785f79df7839d4825/markdown_preview/constants.py#L15)). However, gedit and most editors recognize 3 hyphens (`---`) as enough to constitute a page break.

**Comment by maoschanz** [comment]
Gedit "recognizes" various things (e.g. various ways to underline titles) but my reference is what the python library translating md to html recognizes as an horizontal rule

**Comment by ArcWandx86** [comment]
I think defining it as 3 would be better, since defining it as 3 also picks up ones that are 4 long, but defining it as 4 doesn't pick up the ones that are 3 long.

**Comment by maoschanz** [comment]
Ok my bad, i thought the python3-markdown library was following a standard with 4 hyphens but you're right it's 3, i'll change that

Concerning the "splitter" preference, it looks like something i started to implement and then forgot about it, the code is not finished at all... it will be for the version 3.0 i guess
