### ISSUE TITLE
[documentation] 'live' editing of svg files.

### ISSUE THREAD

**Issue by splace** [maoschanz/gedit-plugin-markdown_preview#39]
have looked around for a 'live' text based svg editor, (for me graphical editors always made poor quality/inflexible/feature missing code.)

so came here hoping this might work. very happy it did.

i did guess editing svg embedded in html would work, but bit surprised it also works for standalone svg files.

![Screenshot at 2022-02-22 14-32-10](https://user-images.githubusercontent.com/1234848/155155219-1bc98416-e98b-4747-8f9c-84ffbb1414cb.png)

and i guess this also works for canvas and others...

so i would say this should be documented.(maybe a new repo with a name reflecting this?)

**Comment by maoschanz** [comment]
interesting, i didn't know lol

**Comment by maoschanz** [comment]
FYI it works because it's very stupid so it thinks any ".html" file is a legit HTML document

**Comment by splace** [comment]
i think, how i got this; was that i loaded an 'html' file with embedded svg, then edited away the html to leave the pure svg, then renamed the file.

i think it all works if you are just editing embedded svg, as i originally thought, its just not as nice.

**Comment by maoschanz** [comment]
the fix to preview SVG without any file naming trick will be released with the version 3.0 of the plugin, meanwhile i don't want to confuse people with too much documentation, i just vaguely mention that it's possible in the readme

**Comment by splace** [comment]
@maoschanz i did wonder, as far as clarity is concerned, if a new repo would be best, with a name reflecting 'broader' uses? even just for html.

**Comment by maoschanz** [comment]
those file formats are supported "by accident" because i render markdown in a pretty classic webkit webview *(if the document has links, you could actually browse the web within gedit from there lol, which isn't secure btw)*, i don't really develop them as features: my commit here is just whitelisting SVG in the same way i whitelisted HTML
