### ISSUE TITLE
Missing dependency required for installation.

### ISSUE THREAD

**Issue by VentGrey** [maoschanz/gedit-plugin-markdown_preview#45]
The `README.md` file lists the needed dependencies to successfully build and install the plugin. However on a new Debian system I found there is a missing dependency not listed:

```
gedit-plugin-markdown_preview-2.0 : ./install.sh 
Checking if adequate folders exist…
Installing setting schemas in /home/ventgrey/.local/share/glib-2.0/schemas
./install.sh: línea 17: glib-compile-schemas: orden no encontrada
Installing plugin files in /home/ventgrey/.local/share/gedit/plugins
Done.
```

This can be solved by installing `libglib2.0-bin`

Thank you for your time and hard work on this project :)

**Comment by maoschanz** [comment]
thanks i'll fix that (and add a message about it in the script maybe)

**Comment by VentGrey** [comment]
Should I close this? :thinking:
