### ISSUE TITLE
Don't open the Markdown preview sidepane automatically

### ISSUE THREAD

**Issue by sojusnik** [maoschanz/gedit-plugin-markdown_preview#7]
I've pulled the latest master branch to play a little bit around and noticed that whenever I open a file with an .md ending, the sidepane with the Markdown preview is opened too. This is quite annoying, since I switch a lot between tabs and tab groups (ctrl+alt+n) and every time I get back to the .md file, the sidepane is opened again, if it was closed before.

I therefore propose to implement an option that will allow the user to turn this behavior on and off respectively. The appropriate setting could be called "Show Markdown preview on opening a Markdown file". Additionally your plugin should remember the state of the sidepane for each file – when you close the pane, then it should stay so, if you switch back to it.

**Comment by maoschanz** [comment]
It was already the behavior of the plugin before. What is new is auto-hiding the panel if no other plugin is opened in it

>I therefore propose to implement an option that will allow the user to turn this behavior on and off respectively.

Ok 

>your plugin should remember the state of the sidepane for each file

Not ok, it doesn't even look possible imo

**Comment by sojusnik** [comment]
> > your plugin should remember the state of the sidepane for each file
> 
> Not ok, it doesn't even look possible imo

This actually isn't that important, if the other option is implemented. It's always better to keep it simple. Thanks again!

**Comment by sojusnik** [comment]
That was a fast one, thanks!

Now I observe the following: If "automatically show/hide panel is disabled", and the panel is on "automatically reload", then the panel closes itself every time I change something in the text.

**Comment by sojusnik** [comment]
The recent version works better, but has some flaws:

1. The preview isn't shown when the sidebar is opened, only after a refresh or a text change
2. If a file is opened from the quick open menu, then the preview doesn't work at all

Watch [this](https://mega.nz/#!K8o3BQLb!cRGUws3w_jzrKockyR3W7ai9WfZI9FfpetldUFc1D3Q) screencast for a better demonstration.
