### ISSUE TITLE
Links are opened internally

### ISSUE THREAD

**Issue by sojusnik** [maoschanz/gedit-plugin-markdown_preview#8]
When clicking on a link in the preview window, then it will be opened internally – in the side pane itself. Normally such links should be opened externally – in a dedicated browser like Firefox.

**Comment by maoschanz** [comment]
I prefer it that way, it's quicker to open. I didn't try to add more things to the right-click yet but until i do you still can copy the link

**Comment by sojusnik** [comment]
I get the rationale, but it's imho unpractical, as shown [here](https://mega.nz/#!yk5EnIAI!5c-fQQCMl51E-1vgDSK8nYMiPqMpms_Fgpu66-957c0).

**Comment by maoschanz** [comment]
i find it very practical, following links without having to load my full Chrome with 65 tabs looks fine to me.

I just added an item to the right-click menu which open links or images in the default browser
